config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # read all tasks
   get '/tasks', to: 'tasks#index'
  # read a task
   get '/tasks/new', to: 'tasks#new'
   post '/tasks', to: 'tasks#create'
   get '/tasks/:id', to: 'tasks#show', as: 'task'
  # create a task

  # update a task
   get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
   patch '/tasks/:id', to: 'tasks#update'
  # delete a task
   delete '/tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
    # @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1 class="list-center"><%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.label :completed %>
<%= f.check_box :completed, {}, true, false %>
<%= f.submit %>
<% end %></h1>

app/views/tasks/edit.html.erb
<%= render 'form', tasj: @task %>

app/views/tasks/index.html.erb
<h1 id="task-center">My Tasks 🗒</h1>
<ul class="list-center">
  <% @tasks.each do |task| %>
    <li class="list-center">
      <h2 class="list-center">
        <%= link_to task.title, task_path(task)%>
      </h2>
    </li>
  <% end %>
  <h3 class="btn-center"><%=link_to "+ Add a new task ❔", tasks_new_path %></h3>
</ul>

app/views/tasks/new.html.erb
<%= render 'form', tasj: @task %>

app/views/tasks/show.html.erb
<h1 id= "task-center" label= "Title"><%= @task.title %></h1>
<h2 class="list-center"label="Details"><%= @task.details %></h2>
<h2 class="list-center" label="Completed"><%= @task.completed %></h2>

<h3 class="btn-center"><%=link_to "Go back", tasks_path %></h3>
<h3 class="btn-center"><%=link_to "Edit", edit_task_path %></h3>
<h3 class="btn-center"><%= link_to "Delete Task",
  task_path(@task),
  method: :delete,
  data: { confirm: "Are you sure ?"}%></h3>